version: "3.3"

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.229.0/24"

services:
  postgres:
    image: postgres:13
    restart: always
    networks:
      my_network:
        ipv4_address: 172.16.229.9
    shm_size: 128mb
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devPassword

    ports:
      - 5432:5432

    volumes:
      - "./db/data/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    networks:
      my_network:
        ipv4_address: 172.16.229.7
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@mail.com #admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=devPassword
    ports:
      - 5050:80

  mysql:
    image: mysql:8.0
    container_name: "mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=my_store
      # - MYSQL_USER=devuser
      # - MYSQL_PASSWORD=devPassword
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=devPassword
      - MYSQL_PORT=3306
      - MYSQL_MAX_CONNECTIONS=99
    volumes:
      - "./db/data/mysql_data:/var/lib/mysql"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin"
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "devPassword"
      # PMA_USER: "devuser"
      # PMA_PASSWORD: "devPassword"
      # PMA_THEME: "default"
      # APACHE_PORT: "8080"
# para abrir postgres en la terminal como si fuera ssh
# docker-compose exec postgres bash
# luego para conectarnos a la base de datos
# psql -h localhost -d <my_data_base> -U <usuario>

# psql -h localhost -d my_store -U devuser
# \d+ para ver las tabla
#  \q para salir de la base de datos
